Repository torizon/vscode-torizon-templates, pull requests merged in 2023-09, with the labels that each got.

#107 python3Pyside2QML: Fix missing rsync on Dockerfile
  python3Pyside2QML/Dockerfile
Labels: bug

#109 `torizoncore-dev` Series
  scripts/zygote.ps1
Labels: bug, enhancement, feature

#110 tasks: Remove duplicated pull(run)-container-torizon-debug-amd64 tasks
  assets/tasks/common.json
Labels: enhancement

#111 templates: Add maintainence policy
  CONTRIBUTING.md
  templates.json
Labels: enhancement

#120 rustSlint/cppSlint: bump to Slint v1.2.1 base images
  cppSlint/Dockerfile
  cppSlint/Dockerfile.debug
  cppSlint/Dockerfile.sdk
  rustSlint/Dockerfile
  rustSlint/Dockerfile.debug
  rustSlint/Dockerfile.sdk
Labels: bug, maintenance
