Repository torizon/vscode-torizon-templates, pull requests merged in 2023-08, with the labels that each got.

#93 cppQML: c_cpp_properties: Update cppStandard to gnu++17
  cppQML/.conf/update.json
  cppQML/.vscode/c_cpp_properties.json
Labels: bug

#91 tasks: Python: Upgrade pip on the host if it has version lower than 23
  python3Console/.vscode/tasks.json
  python3Pyside2QML/.vscode/tasks.json
Labels: enhancement

#103 scripts: torizoncore-dev: Maintainance
  .gitignore
  scripts/container/Containerfile.dev
  scripts/container/Containerfile.gitlab
  scripts/node/apollox-0.0.91.tgz
  scripts/node/apollox-0.0.99.tgz
Labels: maintenance
